sudo: required
services:
    - docker
env:
    global:
        - SHA=$(git rev-parse HEAD)
        - CLOUDSDK_CORE_DISABLE_PROMPTS=1
        - secure: "GepyEX5ZsrWhE35WzbuWiUZ5Et0+eS+NW59DwGoervojt8j644LLdqmVxnRvcvkPbethR1OvFnAyBukkm/LNEE2tDdGKWFnzYXVTpp1d496cV4JbyWcG4de/+4Sw8HV7dwREP0wbrghU+Wu3Filfi4fB/WZf39EZu+GvbTUPYkiyW/adbgRNPrAAncQb3yulymDbD9Z3YFm74Riu0EADXIH8LBUO2l8n7XIbPN4kfBCG0A0KS3Bgi02Y8pR14J9WWq7YiXzpZUPwJmnOOlfmnB+cKqW7P+k+FTIn02Z/+mB60lSDNGsXlDdWEw4CzJBa4eUr3DXq31Bk+vK6r276ajFxx8wywCHv88Boi7OYo81eMX2GwXqF1NnSWUbIjjpgKFT2gaQkzOL28v6gXcQ8F9S79yhhoEmECcvfsdTSOEckRZZqGYmWhGbhO5AQyaSWLI7B3tEp5J9SsEm6lJvrgb/HfD8gRZ+/EjXVHB9a7MUvxwmyF70wScT27M/DAxw6EGnoZAqnGLiC8F3Ztqp1AFKAqdZ2gsWB/63dYFVYiJUC+CJ2BMHzB7ChLeCkrLzz1tP4FIB/wEKrO2Nte9hjdsiZZoT//4R6X9n/iL/QuLkeEWKFNgBSeb00PNVfgIbo0Ekc/oBRbs8k7A78vyhnAJAuhTPK9EKE2FqmJShycOs="
before_install:
    - openssl aes-256-cbc -k "$gc_travis_sa_pwd" -in service-account.json.enc -out service-account.json -d
    - curl https://sdk.cloud.google.com | bash > /dev/null;
    - source $HOME/google-cloud-sdk/path.bash.inc
    - gcloud componenets update kubectl 
    - gcloud auth activate-service-account --key-file service-account.json
    - gcloud config set project lively-ace-262416
    - gcloud config set compute/zone asia-south1-a
    - gcloud container clusters get-credentials docker-k8s-complete-guide
    - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_USERNAME" --password-stdin
    - docker build -t indefsystems/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true indefsystems/react-test npm test

deploy:
    provider: script
    script: bash ./deploy.sh
    on:
        branch: master
