apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: k8s-ktgts-com-tls
spec:
  secretName: k8s-ktgts-com
  issuerRef: 
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: k8s.ktgts.com
  dnsNames:
    - k8s.ktgts.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - k8s.ktgts.com

  